import { Injectable } from '@angular/core';
import { MilestoneObservation } from '../dtos/milestone-observation.dto';

@Injectable({ providedIn: 'root' })
export class MilestoneUtils {
    milestoneOnservations: MilestoneObservation[];

    constructor() {
        // TO DO: List everything from EYLF
        this.milestoneOnservations = [
            new MilestoneObservation('Birth to 4 months', 'Physical', 'moves whole body'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'squirms, arms wave, legs move up and down'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'eating and sleeping patterns'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'startle reflex when placed unwrapped on flat surface/when hears loud noise'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'head turns to side when cheek touched'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'sucking motions with mouth (seeking nipple)'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'responds to gentle touching, cuddling, rocking'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'shuts eyes tight in bright sunlight'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'able to lift head and chest when laying on stomach'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'begins to roll from side to side'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'starts reaching to swipe at dangling objects'),
            new MilestoneObservation('Birth to 4 months', 'Physical', 'able to grasp object put into hands'),
            new MilestoneObservation('Birth to 4 months', 'Social', 'smiles and laughs'),
            new MilestoneObservation('Birth to 4 months', 'Social', 'makes eye contact when held with face about 20cm from face of adult looking at them'),
            new MilestoneObservation('Birth to 4 months', 'Social', 'may sleep most of the time'),
            new MilestoneObservation('Birth to 4 months', 'Social', 'alert and preoccupied with faces'),
            new MilestoneObservation('Birth to 4 months', 'Social', 'moves head to sound of voices'),
            new MilestoneObservation('Birth to 4 months', 'Emotional', 'bonding'),
            new MilestoneObservation('Birth to 4 months', 'Emotional', 'cries (peaks about six to eight weeks) and levels off about 12-14 weeks'),
            new MilestoneObservation('Birth to 4 months', 'Emotional', 'cries when hungry or uncomfortable and usually stops when held'),
            new MilestoneObservation('Birth to 4 months', 'Emotional', 'shows excitement as parent prepared to feed'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'smiles and laughs'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'looks toward direction of sound'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'eyes track slow moving target for brief period'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'looks at edges, patterns with light/dark contrast and faces'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'imitates adult tongue movements when being held/talked to'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'learns through sensory experiences'),
            new MilestoneObservation('Birth to 4 months', 'Cognitive', 'repeats actions but unaware of ability to cause actions'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'expresses needs'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'cries'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'when content makes small throaty noises'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'soothed by sound of voice or by low rhythmic sounds'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'imitates adult tongue movements when being held and talked to'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'may start to copy sounds'),
            new MilestoneObservation('Birth to 4 months', 'Language', 'coos and gurgles'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'floppy or stiff'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'cries a lot'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'arches his/her back'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'not responding to sounds'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'not showing interest or responding when played with'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'not feeding as expected'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'not starting to make sounds'),
            new MilestoneObservation('Birth to 4 months', 'Seek advice', 'not responding to familiar faces'),

            new MilestoneObservation('4 to 8 months', 'Physical', 'plays with feet and toes'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'makes effort to sit alone, but needs hand support'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'raises head and chest when lying on stomach'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'makes crawling movements when lying on stomach'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'rolls from back to stomach'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'reachs for and grasp objects, using one hand to grasp'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'eyes smoothly follow object or person'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'crawling movements using both hands and feet'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'able to take weight on feet when standing'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'watch activities across room - eyes move in unison'),
            new MilestoneObservation('4 to 8 months', 'Physical', 'turns head to sound of voices'),
            new MilestoneObservation('4 to 8 months', 'Social', 'reacts with arousal, attention or approach to presence of another baby or young child'),
            new MilestoneObservation('4 to 8 months', 'Social', 'responds to own name'),
            new MilestoneObservation('4 to 8 months', 'Social', 'smiles often and shows excitement when sees preparations being made for meals or for bath'),
            new MilestoneObservation('4 to 8 months', 'Social', 'recognises familiar people and stretches arms to be picked up'),
            new MilestoneObservation('4 to 8 months', 'Emotional', 'becoming more settled in eating and sleeping patterns'),
            new MilestoneObservation('4 to 8 months', 'Emotional', 'laughs, especially in social interactions'),
            new MilestoneObservation('4 to 8 months', 'Emotional', 'may soothe self when tired or upset by sucking thumb or dummy'),
            new MilestoneObservation('4 to 8 months', 'Emotional', 'begins to show wariness of strangers'),
            new MilestoneObservation('4 to 8 months', 'Emotional', 'may fret when parent leaves the room'),
            new MilestoneObservation('4 to 8 months', 'Emotional', 'happy to see faces they know'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'swipes at dangling objects'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'shakes and stares at toy placed in hand'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'becomes bored if left alone for long periods of time'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'repeats accidently caused actions that are interesting'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'enjoys games such as peek-a-boo or pat-a-cake'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'will search for partly hidden object'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'able to coordinate looking, hearing and touching'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'enjoys toys, banging objects, scrunching paper'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'explores objects by looking at and mouthing them'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'develops preferences for foods'),
            new MilestoneObservation('4 to 8 months', 'Cognitive', 'explores objects with mouth'),
            new MilestoneObservation('4 to 8 months', 'Language', 'enjoys games such as peek-a-boo or pat-a-cake'),
            new MilestoneObservation('4 to 8 months', 'Language', 'babbles and repeat sounds'),
            new MilestoneObservation('4 to 8 months', 'Language', 'makes talking sounds in response to others talking'),
            new MilestoneObservation('4 to 8 months', 'Language', 'copies sounds'),
            new MilestoneObservation('4 to 8 months', 'Language', 'smiles and babbles at own image in mirror'),
            new MilestoneObservation('4 to 8 months', 'Language', 'responds to own name'),
            new MilestoneObservation('4 to 8 months', 'Seek advice', 'not learning to make sounds'),
            new MilestoneObservation('4 to 8 months', 'Seek advice', 'not responding to familiar faces'),
            new MilestoneObservation('4 to 8 months', 'Seek advice', 'not learning to roll when playing on floor'),
            new MilestoneObservation('4 to 8 months', 'Seek advice', 'not responsive to carers'),
            new MilestoneObservation('4 to 8 months', 'Seek advice', 'not babbling and making sounds'),
            new MilestoneObservation('4 to 8 months', 'Seek advice', 'not playing with feet/swapping objects between hands'),

            new MilestoneObservation('8 to 12 months', 'Physical', 'pulls self to standing position when hands held'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'raises self to sitting position'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'sits without support'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'stands by pulling themself up using furniture'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'stepping movements around furniture'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'successfully reach out and grasp toy'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'transfers objects from hand to hand'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'picks up and pokes small objects with thumb and finger'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'picks up and throws small objects'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'holds biscuit or bottle'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'crawls'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'mature crawling (quick and fluent)'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'may stand alone momentarily'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'may attempt to crawl up stairs'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'grasps spoon in palm, but poor aim of food to mouth'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'uses hands to feed self'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'alerts peripheral vision'),
            new MilestoneObservation('8 to 12 months', 'Physical', 'rolls ball and crawls to retrieve'),
            new MilestoneObservation('8 to 12 months', 'Social', 'shows definite anxiety or wariness at appearance of strangers'),
            new MilestoneObservation('8 to 12 months', 'Emotional', 'actively seeks to be next to parent or principal caregiver'),
            new MilestoneObservation('8 to 12 months', 'Emotional', 'shows signs of anxiety or stress if parent goes away'),
            new MilestoneObservation('8 to 12 months', 'Emotional', 'offers toy to adult but does not release it'),
            new MilestoneObservation('8 to 12 months', 'Emotional', 'shows signs of empathy to distress of another (but often soothes self)'),
            new MilestoneObservation('8 to 12 months', 'Emotional', 'actively explores and plays when parent present, returning now and then for assurance and interaction'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'moves obstacle to get at desired toy'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'bangs two objects held in hands together'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'responds to own name'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'makes gestures to communicate and to symbolise objects, e.g. points to something they want'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'seems to understand some things parent or familiar adults say to them'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'drops toys to be retrieved, handed back, then dropped again/looks in direction of dropped toy'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'smiles at image in mirror'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'likes playing with water'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'shows interest in picture books'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'understands gestures/responds to ‘bye bye’'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'listens with pleasure to sound-making toys and music'),
            new MilestoneObservation('8 to 12 months', 'Cognitive', 'notices difference and shows surprise'),
            new MilestoneObservation('8 to 12 months', 'Language', 'responds to own name being called, family names and familiar objects'),
            new MilestoneObservation('8 to 12 months', 'Language', 'babbles tunefully'),
            new MilestoneObservation('8 to 12 months', 'Language', 'says words like ‘dada’ or ‘mama’'),
            new MilestoneObservation('8 to 12 months', 'Language', 'waves goodbye'),
            new MilestoneObservation('8 to 12 months', 'Language', 'imitates hand clapping'),
            new MilestoneObservation('8 to 12 months', 'Language', 'imitates actions and sounds'),
            new MilestoneObservation('8 to 12 months', 'Language', 'enjoys finger-rhymes'),
            new MilestoneObservation('8 to 12 months', 'Language', 'shouts to attract attention'),
            new MilestoneObservation('8 to 12 months', 'Language', 'vocalises loudly using most vowels and consonants - sounding like conversation'),
            new MilestoneObservation('8 to 12 months', 'Seek advice', 'not responsive to carers'),
            new MilestoneObservation('8 to 12 months', 'Seek advice', 'not babbling and making sounds'),
            new MilestoneObservation('8 to 12 months', 'Seek advice', 'not beginning to sit, crawl, or pull to stand'),
            new MilestoneObservation('8 to 12 months', 'Seek advice', 'not playing with feet, swapping objects between hands'),
            new MilestoneObservation('8 to 12 months', 'Seek advice', 'not interested in holding toys'),
            new MilestoneObservation('8 to 12 months', 'Seek advice', 'not learning to eat solids'),

            new MilestoneObservation('1 to 2 years', 'Physical', 'walks, climbs and runs'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'takes two to three steps without support, legs wide and hands up for balance'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'crawls up steps'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'dances in place to music'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'climbs onto chair'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'kicks and throws a ball'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'feeds themselves'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'begins to run (hurried walk)'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'scribbles with pencil or crayon held in fist'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'turns pages of book, two or three pages at a time'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'rolls large ball, using both hands and arms'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'finger feeds efficiently'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'begins to walk alone in a ‘tottering way’, with frequent falls'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'squats to pick up an object'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'reverts to crawling if in a hurry'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'can drink from a cup'),
            new MilestoneObservation('1 to 2 years', 'Physical', 'tries to use spoon/fork'),
            new MilestoneObservation('1 to 2 years', 'Social', 'begins to cooperate when playing'),
            new MilestoneObservation('1 to 2 years', 'Social', 'may play alongside other toddlers, doing what they do but without seeming to interact (parallel play)'),
            new MilestoneObservation('1 to 2 years', 'Social', 'curious and energetic, but depends on adult presence for reassurance'),
            new MilestoneObservation('1 to 2 years', 'Emotional', 'may show anxiety when separating from significant people in their lives'),
            new MilestoneObservation('1 to 2 years', 'Emotional', 'seeks comfort when upset or afraid'),
            new MilestoneObservation('1 to 2 years', 'Emotional', 'takes cue from parent or principal carer regarding attitude to a stranger'),
            new MilestoneObservation('1 to 2 years', 'Emotional', 'may ‘lose control’ of self when tired or frustrated'),
            new MilestoneObservation('1 to 2 years', 'Emotional', 'assists another in distress by patting, making sympathetic noises or offering material objects'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'repeats actions that lead to interesting/predictable results, e.g. bangs spoon on saucepan'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'points to objects when named'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'knows some body parts'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'points to body parts in a game'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'recognises self in photo or mirror'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'mimics household activities, e.g. bathing baby, sweeping floor'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'may signal when s/he has finished their toileting'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'spends a lot of time exploring and manipulating objects, putting in mouth, shaking and banging them'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'stacks and knocks over items'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'selects games and puts them away'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'calls self by name, uses ‘I’, ‘mine’, ‘I do it myself’'),
            new MilestoneObservation('1 to 2 years', 'Cognitive', 'will search for hidden toys'),
            new MilestoneObservation('1 to 2 years', 'Language', 'comprehends and follows simple questions/commands'),
            new MilestoneObservation('1 to 2 years', 'Language', 'says first name'),
            new MilestoneObservation('1 to 2 years', 'Language', 'says many words (mostly naming words)'),
            new MilestoneObservation('1 to 2 years', 'Language', 'begins to use one to two word sentences, e.g. ”want milk”'),
            new MilestoneObservation('1 to 2 years', 'Language', 'reciprocal imitation of another toddler: will imitate each other’s actions'),
            new MilestoneObservation('1 to 2 years', 'Language', 'enjoys rhymes and songs'),
            new MilestoneObservation('1 to 2 years', 'Seek advice', 'not using words or actions to communicate such as waving or raising arms to be lifted'),
            new MilestoneObservation('1 to 2 years', 'Seek advice', 'not wanting to move around'),
            new MilestoneObservation('1 to 2 years', 'Seek advice', 'not responding to others'),
            new MilestoneObservation('1 to 2 years', 'Seek advice', 'not seeking attention of familiar people'),

            new MilestoneObservation('2 to 3 years', 'Physical', 'walks, runs, climbs, kicks and jumps easily'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'uses steps one at a time'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'squats to play and rises without using hands'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'catches ball rolled to him/her'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'walks into a ball to kick it'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'jumps from low step or over low objects'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'attempts to balance on one foot'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'avoids obstacles'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'able to open doors'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'stops readily'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'moves about moving to music'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'turns pages one at a time'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'holds crayon with fingers'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'uses a pencil to draw or scribble in circles and lines'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'gets dressed with help'),
            new MilestoneObservation('2 to 3 years', 'Physical', 'self-feeds using utensils and a cup'),
            new MilestoneObservation('2 to 3 years', 'Social', 'plays with other children'),
            new MilestoneObservation('2 to 3 years', 'Social', 'simple make believe play'),
            new MilestoneObservation('2 to 3 years', 'Social', 'may prefer same sex playmates and toys'),
            new MilestoneObservation('2 to 3 years', 'Social', 'unlikely to share toys without protest'),
            new MilestoneObservation('2 to 3 years', 'Emotional', 'shows strong attachment to a parent (or main family carer)'),
            new MilestoneObservation('2 to 3 years', 'Emotional', 'shows distress and protest when they leave and wants that person to do things for them'),
            new MilestoneObservation('2 to 3 years', 'Emotional', 'begins to show guilt or remorse for misdeeds'),
            new MilestoneObservation('2 to 3 years', 'Emotional', 'may be less likely to willingly share toys with peers'),
            new MilestoneObservation('2 to 3 years', 'Emotional', 'demands adult attention'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'builds tower of five to seven objects'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'lines up objects in ‘train’ fashion'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'recognises and identifies common objects and pictures by pointing'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'enjoys playing with sand, water, dough; explores what these materials can do more than making things with them'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'uses symbolic play, e.g. use a block as a car'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'shows knowledge of gender-role stereotypes'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'identifies picture as a boy or girl'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'engages in making believe and pretend play'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'begins to count with numbers'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'recognises similarities and differences'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'imitates rhythms and animal movements'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'becoming aware of space through physical activity'),
            new MilestoneObservation('2 to 3 years', 'Cognitive', 'can follow two or more directions'),
            new MilestoneObservation('2 to 3 years', 'Language', 'uses two or three words together, e.g. “go potty now”'),
            new MilestoneObservation('2 to 3 years', 'Language', '‘explosion’ of vocabulary and use of correct grammatical forms of language'),
            new MilestoneObservation('2 to 3 years', 'Language', 'refers to self by name and often says ‘mine’'),
            new MilestoneObservation('2 to 3 years', 'Language', 'asks lots of questions'),
            new MilestoneObservation('2 to 3 years', 'Language', 'uses pronouns and prepositions, simple sentences and phrases'),
            new MilestoneObservation('2 to 3 years', 'Language', 'labels own gender'),
            new MilestoneObservation('2 to 3 years', 'Language', 'copies words and actions'),
            new MilestoneObservation('2 to 3 years', 'Language', 'makes music, sing and dance'),
            new MilestoneObservation('2 to 3 years', 'Language', 'likes listening to stories and books'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'not interested in playing'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'falling a lot'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'finds it hard to use small objects'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'not understanding simple instructions'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'not using many words'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'not joining words in meaningful phrases'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'not interested in food'),
            new MilestoneObservation('2 to 3 years', 'Seek advice', 'not interested in others'),

            new MilestoneObservation('3 to 5 years', 'Physical', 'dresses and undresses with little help'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'hops, jumps and runs with ease'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'climbs steps with alternating feet'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'gallops and skips by leading with one foot'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'transfers weight forward to throw ball'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'attempts to catch ball with hands'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'climbs playground equipment with increasing agility'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'holds crayon/pencil etc. between thumb and first two fingers'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'exhibits hand preference'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'imitates variety of shapes in drawing, e.g. circles'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'independently cuts paper with scissors'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'toilet themselves'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'feeds self with minimum spills'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'dresses/undresses with minimal assistance'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'walks and runs more smoothly'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'enjoys learning simple rhythm and movement routines'),
            new MilestoneObservation('3 to 5 years', 'Physical', 'develops ability to toilet train at night'),
            new MilestoneObservation('3 to 5 years', 'Social', 'enjoys playing with other children'),
            new MilestoneObservation('3 to 5 years', 'Social', 'may have a particular friend'),
            new MilestoneObservation('3 to 5 years', 'Social', 'shares, smiles and cooperates with peers'),
            new MilestoneObservation('3 to 5 years', 'Social', 'jointly manipulates objects with one or two other peers'),
            new MilestoneObservation('3 to 5 years', 'Social', 'develops independence and social skills they will use for learning and getting on with others at preschool and school'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'understands when someone is hurt and comforts them'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'attains gender stability (sure she/he is a girl/boy)'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'may show stronger preference for same-sex playmates'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'may enforce gender-role norms with peers'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'may show bouts of aggression with peers'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'likes to give and receive affection from parents'),
            new MilestoneObservation('3 to 5 years', 'Emotional', 'may praise themselves and be boastful'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'understands opposites (e.g. big/little) and positional words (middle, end)'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'uses objects and materials to build or construct things, e.g. block tower, puzzle, clay, sand and water'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'builds tower eight to ten blocks'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'answers simple questions'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'counts five to ten things'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'has a longer attention span'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'talks to self during play - to help guide what he/she does'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'follows simple instructions'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'follows simple rules and enjoys helping'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'may write some numbers and letters'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'engages in dramatic play, taking on pretend character roles'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'recalls events correctly'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'counts by rote, having memorised numbers'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'touches objects to count - starting to understand relationship between numbers and objects'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'can recount a recent story'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'copies letters and may write some unprompted'),
            new MilestoneObservation('3 to 5 years', 'Cognitive', 'can match and name some colours'),
            new MilestoneObservation('3 to 5 years', 'Language', 'speaks in sentences and use many different words'),
            new MilestoneObservation('3 to 5 years', 'Language', 'answers simple questions'),
            new MilestoneObservation('3 to 5 years', 'Language', 'asks many questions'),
            new MilestoneObservation('3 to 5 years', 'Language', 'tells stories'),
            new MilestoneObservation('3 to 5 years', 'Language', 'talks constantly'),
            new MilestoneObservation('3 to 5 years', 'Language', 'enjoys talking and may like to experiment with new words'),
            new MilestoneObservation('3 to 5 years', 'Language', 'uses adult forms of speech'),
            new MilestoneObservation('3 to 5 years', 'Language', 'takes part in conversations'),
            new MilestoneObservation('3 to 5 years', 'Language', 'enjoys jokes, rhymes and stories'),
            new MilestoneObservation('3 to 5 years', 'Language', 'will assert self with words'),
            new MilestoneObservation('3 to 5 years', 'Seek advice', 'not understood by others'),
            new MilestoneObservation('3 to 5 years', 'Seek advice', 'has speech fluency problems or stammering'),
            new MilestoneObservation('3 to 5 years', 'Seek advice', 'not playing with other children'),
            new MilestoneObservation('3 to 5 years', 'Seek advice', 'not able to have a conversation'),
            new MilestoneObservation('3 to 5 years', 'Seek advice', 'not able to go to the toilet or wash him/herself')
        ];
    }

    getObservations(): MilestoneObservation[] {
        return this.milestoneOnservations;
    }

    getObservationsByAgeAndArea(age_group: string, developmental_area: string): MilestoneObservation[] {
        return this.milestoneOnservations.filter(o => o.age_group === age_group && o.developmental_area === developmental_area);
    }

    getDevelopmentalAreas(): string[] {
        return [
            'Physical',
            'Social',
            'Emotional',
            'Cognitive',
            'Language'
        ];
    }
}
